global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "monitoring-service"
    static_configs:
      - targets: ["localhost:5009"]

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

rule_files:
  - "alert_rules.yml"
