definitions:
  models.Review:
    properties:
      comment:
        type: string
      id:
        type: integer
      place_name:
        type: string
      rating:
        type: integer
      user_id:
        type: string
    type: object
info:
  contact: {}
  description: API para obtener reseñas de lugares turísticos.
  title: Microservicio de Consulta de Reseñas
  version: "1.0"
paths:
  /reviews:
    get:
      description: Devuelve un listado de todas las reseñas almacenadas en la base
        de datos.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Review'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Obtiene todas las reseñas
      tags:
      - Reviews
  /reviews/{id}:
    get:
      description: Devuelve una reseña según el ID proporcionado en la URL.
      parameters:
      - description: ID de la reseña
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Review'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Obtiene una reseña específica
      tags:
      - Reviews
  /reviews/place/{place_id}:
    get:
      description: Devuelve todas las reseñas asociadas a un lugar, según el ID del
        lugar.
      parameters:
      - description: ID del lugar turístico
        in: path
        name: place_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Review'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Obtiene reseñas de un lugar turístico
      tags:
      - Reviews
swagger: "2.0"
