definitions:
  models.Review:
    description: Modelo de actualización de reseña
    properties:
      comment:
        description: Nuevo comentario
        type: string
      id:
        description: ID de la reseña
        type: integer
      rating:
        description: Nueva puntuación del lugar
        type: number
    type: object
info:
  contact: {}
  description: API para actualizar reseñas de lugares turísticos
  title: Microservicio de Actualización de Reseñas
  version: "1.0"
paths:
  /reviews/{id}:
    put:
      consumes:
      - application/json
      description: Permite actualizar una reseña existente por su ID
      parameters:
      - description: ID de la reseña
        in: path
        name: id
        required: true
        type: integer
      - description: Datos actualizados
        in: body
        name: review
        required: true
        schema:
          $ref: '#/definitions/models.Review'
      produces:
      - application/json
      responses:
        "200":
          description: Reseña actualizada correctamente
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Error en la solicitud
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Reseña no encontrada
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Actualizar reseña
      tags:
      - Reseñas
swagger: "2.0"
