name: Deploy MongoDB to EC2

on:
  push:
    paths:
      - '.github/workflows/mongo-ci.yml'
    branches: [ "QA" ]
  pull_request:
    paths:
      - '.github/workflows/mongo-ci.yml'
    branches: 
      - "QA"
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Install dependeces
      - name: Install dependences
        uses: pip install -r requirements.txt
      
      # 3 Login Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-image:latest

      - name: Logout from Docker Hub
        run: docker logout

      - name: Connect to EC2 and pull repository
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /path/to/your-repo
            git pull origin main